apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/dex-app/charts/dex
  contents:
  - path: .
    helmChart:
      name: dex
      version: "0.23.0"
      repository:
        url: https://charts.dexidp.io
