apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-k8s-authenticator
  labels:
{{ include "dex.labels" . | indent 4 }}
    app.kubernetes.io/component: dex-k8s-authenticator
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: "/"
    debug: "false"
    logo_uri: {{ .logoUrl }}
    idp_ca_pem: {{ toYaml .Values.Installation.V1.Secret.Kubernetes.CAPem | indent 4 }}
    clusters:
    - name: {{ .Values.Installation.V1.Name }}
      short_description: "{{ .Values.Installation.V1.Name }} control-plane"
      description: "{{ .Values.Installation.V1.Name }} control-plane cluster customer authentication"
      client_secret: {{ .Values.Installation.V1.Secret.OIDC.ClientSecret }}
      issuer: https://{{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress }}
      k8s_master_uri: https://{{ .Values.Installation.V1.Kubernetes.API.Address }}
      client_id: dex-k8s-authenticator
      redirect_uri: https://{{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}/callback
