apiVersion: v1
kind: Service
metadata:
  name: dex-k8s-authenticator
  labels:
{{ include "dexauthenticator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: dex-k8s-authenticator
    release: {{ .Release.Name }}
