apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex-k8s-authenticator
  labels:
{{ include "dexauthenticator.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    secretName: k8s-dex-authenticator-le
    {{- else }}
    secretName: k8s-dex-authenticator
    {{- end }}
  rules:
  - host: {{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}
    http:
      paths:
      - path: /
        backend:
          serviceName: dex-k8s-authenticator
          servicePort: http
          
