{{- if .Values.networkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "dex.fullname" . }}
  namespace: {{ include "dex.namespace" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "dex.selectorLabels" . | nindent 6 }}
  
  ingress:
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: http
        {{- if .Values.https.enabled }}
        - ports:
            - port: https
        {{- end }}
        {{- if .Values.grpc.enabled }}
        - ports:
            - port: grpc
        {{- end }}
        - ports:
            - port: telemetry
  
  {{- with .Values.networkPolicy.egressRules }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}