{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex
  labels:
{{ include "dex.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress | quote }}
      {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
      secretName: dex-tls-le
      {{- else }}
      secretName: dex-tls
      {{- end }}
  rules:
    - host: {{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: dex
              servicePort: 32000
{{ end }}
