kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: dex
  labels:
{{ include "dex.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: dex
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 5556
      protocol: TCP
  egress:
  - {}
