apiVersion: v1
kind: Service
metadata:
  name: dex
  labels:
{{ include "dex.labels" . | indent 4 }}
    app.kubernetes.io/component: dex
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    targetPort: http
    port: 32000
  selector:
    app.kubernetes.io/component: dex
    app.kubernetes.io/instance: {{ .Release.Name }}
