{{- if .Values.dex.ingress.enabled }}
{{- $fullName := include "dex.fullname" . }}
{{- $svcPort := .Values.dex.service.ports.http.port }}
{{- $host := "" }}
{{- if eq (include "is-workload-cluster" .) "true" }}
{{- $host = printf "dex.%s" .Values.dex.baseDomain }}
{{- else if .Values.dex.isManagementCluster }}
{{- $host = .Values.dex.oidc.issuerAddress }}
{{- else }}
{{- $host = printf "dex.%s" (.Values.dex.baseDomain | default "localhost") }}
{{- end }}
{{- if and .Values.dex.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
{{- if not (hasKey .Values.dex.ingress.annotations "kubernetes.io/ingress.class") }}
{{- $_ := set .Values.dex.ingress.annotations "kubernetes.io/ingress.class" .Values.dex.ingress.className }}
{{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "dex.name" . }}
  namespace: {{ include "dex.namespace" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
  {{- with .Values.dex.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.dex.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.dex.ingress.className }}
  {{- end }}
  {{- if kindIs "slice" .Values.dex.ingress.tls }}
  tls:
    {{- range .Values.dex.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if and (kindIs "map" .Values.dex.ingress.tls) .Values.dex.ingress.tls.letsencrypt }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ include "dex.name" . }}-tls-le
  {{- else if kindIs "map" .Values.dex.ingress.tls }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ include "dex.name" . }}-tls
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "dex.name" . }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ include "dex.name" . }}
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}