{{- if .Values.configSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.configSecretName" . }}
  namespace: {{ include "dex.namespace" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
{{- end }}
