{{- if not .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  name: {{ include "resource.dex.name" . }}-tls
data:
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
{{- end }}
