{{- if not .Values.ingress.tls.letsencrypt }}
{{- if not .Values.ingress.tls.externalSecret.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  name: {{ include "resource.dex.name" . }}-tls
data:
  ca.crt: {{ .Values.ingress.tls.caPemB64 | quote }}
  tls.crt: {{ .Values.ingress.tls.crtPemB64 | quote }}
  tls.key: {{ .Values.ingress.tls.keyPemB64 | quote }}
{{- end }}
{{- end }}
