apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
    {{- include "dex-app.labels.selector" . | nindent 4 }}
  name: {{ include "resource.dex.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.dex.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.dex.name" . }}
    namespace: {{ .Release.Namespace }}
