apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  annotations:
    app.giantswarm.io/secret-checksum: {{ include (print .Template.BasePath "/dex/secret.yaml") . | sha256sum | quote }}
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "dex.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dex.labels.common" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/dex/secret.yaml") . | sha256sum | quote }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "dex.labels.selector" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
            weight: 100
      serviceAccountName: {{ include "resource.dex.name" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: dex
        env:
        {{- if and .Values.proxy .Values.proxy.enabled }}
        {{- if .Values.proxy.http_proxy }}
        - name: HTTP_PROXY
          value: {{ .Values.proxy.http_proxy }}
        {{- end }}
        {{- if .Values.proxy.https_proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy.https_proxy }}
        {{- end }}
        {{- if .Values.proxy.no_proxy }}
        - name: NO_PROXY
          value: {{ .Values.proxy.no_proxy }}
        {{- end }}
        {{- end }}
        - name: KUBERNETES_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{ if .Values.isManagementCluster }}
        image: "{{ .Values.registry.domain }}/{{ .Values.dex.image.name }}:{{ .Chart.AppVersion }}"
        {{ else }}
        image: "{{ .Values.dex.image.registry }}/{{ .Values.dex.image.name }}:{{ .Chart.AppVersion }}"
        {{ end }}
        imagePullPolicy: {{ .Values.dex.image.pullPolicy }}
        command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: metrics
          containerPort: 5558
          protocol: TCP

        livenessProbe:
          httpGet:
            path: "/healthz"
            port: http
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: http
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 1
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | nindent 8 }}
{{- end }}
      volumes:
      - secret:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          secretName: {{ include "resource.dex.name" . }}
        name: config
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | nindent 6 }}
{{- end }}
