{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
    {{- include "dex-app.labels.selector" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls.letsencrypt }}
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    {{- else if ne .Values.ingress.tls.clusterIssuer "" }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- end }}
    {{- if .Values.ingress.externalDNS }}
    {{- if eq (include "is-workload-cluster" .) "true" }}
    external-dns.alpha.kubernetes.io/hostname: dex.{{ .Values.baseDomain }}
    {{- else if .Values.isManagementCluster }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.oidc.issuerAddress }}
    {{- end }}
    giantswarm.io/external-dns: managed
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
      {{- if eq (include "is-workload-cluster" .) "true" }}
        - dex.{{ .Values.baseDomain }}
      {{- else if .Values.isManagementCluster }}
        - {{ .Values.oidc.issuerAddress }}
      {{- end }}
      {{- if .Values.ingress.tls.letsencrypt }}
      secretName: {{ include "resource.dex.name" . }}-tls-le
      {{- else }}
      secretName: {{ include "resource.dex.name" . }}-tls
      {{- end }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ include "resource.dex.name" . }}
                port:
                  number: 32000
{{- else }}
              serviceName: {{ include "resource.dex.name" . }}
              servicePort: 32000
{{- end }}
  {{- if eq (include "is-workload-cluster" .) "true" }}
      host: dex.{{ .Values.baseDomain }}
  {{- else if .Values.isManagementCluster }}
      host: {{ .Values.oidc.issuerAddress }}
  {{- end }}
