{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress | quote }}
      {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
      secretName: {{ include "resource.dex.name" . }}-tls-le
      {{- else }}
      secretName: {{ include "resource.dex.name" . }}-tls
      {{- end }}
  rules:
    - host: {{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "resource.dex.name" . }}
              servicePort: 32000
{{ end }}
