apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls.letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      {{- if .Values.isWorkloadCluster }}
        - dex.{{ .Values.baseDomain }}
      {{- else }}
        - {{ .Values.oidc.issuerAddress }}
      {{- end }}
      {{- if .Values.ingress.tls.letsencrypt }}
      secretName: {{ include "resource.dex.name" . }}-tls-le
      {{- else }}
      secretName: {{ include "resource.dex.name" . }}-tls
      {{- end }}
  rules:
  {{- if .Values.isWorkloadCluster }}
    - host: dex.{{ .Values.baseDomain }}
  {{- else }}
    - host: {{ .Values.oidc.issuerAddress }}
  {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "resource.dex.name" . }}
                port:
                  number: 32000
