{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls.letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
       {{- if .Values.isWorkloadCluster }}
        - {{ .Values.baseDomain | quote }}
      {{- else }}
        - {{ .Values.oidc.issuerAddress | quote }}
      {{- end }}
      {{- if .Values.ingress.tls.letsencrypt }}
      secretName: {{ include "resource.dex.name" . }}-tls-le
      {{- else }}
      secretName: {{ include "resource.dex.name" . }}-tls
      {{- end }}
  rules:
  {{- if .Values.isWorkloadCluster }}
    - host: {{ .Values.baseDomain | quote }}
  {{- else }}
    - host: {{ .Values.oidc.issuerAddress | quote }}
  {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ include "resource.dex.name" . }}
                port:
                  number: 32000
{{- else }}
              serviceName: {{ include "resource.dex.name" . }}
              servicePort: 32000
{{- end }}
