kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.dex.networkPolicy.name" . }}
  labels:
    {{- include "dex-app.labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dex-app.labels.selector" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 5556
      protocol: TCP
    - port: 5558
      protocol: TCP
  egress:
  - {}
