{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "resource.dex.name" . }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      {{- include "dex.labels.common" . | nindent 6 }}
      {{- include "dex-app.labels.selector" . | nindent 4 }}
{{- end }}
