apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  name: {{ include "resource.dex.name" . }}
stringData:
  config.yaml: |-
    web:
      http: 0.0.0.0:5556
      allowedOrigins:
      - {{ .Values.Installation.V1.GiantSwarm.Happa.Address }}
    storage:
      type: kubernetes
      config:
        inCluster: true
    logger:
      level: debug
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    enablePasswordDB: false
    frontend:
      logoURL: http://styleguide.io/o/giantswarm/logo_simplified/giantswarm_logo_simplified.png
    issuer: https://{{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress }}
    expiry:
      signingKeys: "{{ .Values.Installation.V1.GiantSwarm.OIDC.Expiry.SigningKeys }}"
      idTokens: "{{ .Values.Installation.V1.GiantSwarm.OIDC.Expiry.IdTokens }}"
    staticClients:
    - id: {{ .Values.Installation.V1.GiantSwarm.OIDC.StaticClients.GSCLIAuth.ClientID }}
      public: true
      name: gscliauth
      secret: {{ .Values.Installation.V1.Secret.OIDC.StaticClients.GSCLIAuth.Secret }}
    - id: {{ .Values.Installation.V1.GiantSwarm.OIDC.StaticClients.Happa.ClientID }}
      redirectURIs:
      - {{ .Values.Installation.V1.GiantSwarm.OIDC.StaticClients.Happa.Address }}
      - http://localhost:7000/cp-access/callback
      name: happa
      secret: {{ .Values.Installation.V1.Secret.OIDC.StaticClients.Happa.Secret }}
    - id: dex-k8s-authenticator-customer
      redirectURIs:
      - https://{{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}/callback
      name: dex-k8s-authenticator-customer
      secret: {{ .Values.Installation.V1.Secret.OIDC.ClientSecret }}
      trustedPeers:
      - {{ .Values.Installation.V1.GiantSwarm.OIDC.StaticClients.GSCLIAuth.ClientID }}
      - {{ .Values.Installation.V1.GiantSwarm.OIDC.StaticClients.Happa.ClientID }}
    - id: dex-k8s-authenticator-giantswarm
      redirectURIs:
      - https://{{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}/callback
      name: dex-k8s-authenticator-giantswarm
      secret: {{ .Values.Installation.V1.Secret.OIDC.GSClientSecret }}
    connectors:
    - type: google
      id: giantswarm
      name: Google
      config:
        clientID: {{ .Values.Installation.V1.Secret.OIDC.GSConnectorConfig.ClientID }}
        clientSecret: {{ .Values.Installation.V1.Secret.OIDC.GSConnectorConfig.ClientSecret }}
        redirectURI: https://{{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress }}/callback
        serviceAccountFilePath: /data/googleAuth.json
        adminEmail: {{ .Values.Installation.V1.Secret.OIDC.GSConnectorConfig.AdminEmail }}
        groups:
        {{ range $i, $e := .Values.Installation.V1.Secret.OIDC.GSConnectorConfig.Groups }}
        - {{ $e }}
        {{end}}
    - type: {{ .Values.Installation.V1.GiantSwarm.OIDC.Type }}
      id: customer
      name: {{ .Values.Installation.V1.GiantSwarm.OIDC.Name }}
      config:
        {{- .Values.Installation.V1.Secret.OIDC.ConnectorConfig | nindent 8 }}
