apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  name: dex-google-auth
data:
  googleAuth.json: {{ .Values.Installation.V1.Secret.OIDC.GSConnectorConfig.ServiceAccountFile | b64enc }} 


