apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  name: {{ include "resource.dex.name" . }}
stringData:
  config.yaml: |-
    web:
      http: 0.0.0.0:5556
      {{- if (or .Values.services.happa.address .Values.services.grafana.address) }}
      allowedOrigins:
      - {{ .Values.services.happa.address }}
      - {{ .Values.services.grafana.address }}
      {{- end }}
    storage:
      type: kubernetes
      config:
        inCluster: true
    logger:
      level: debug
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    enablePasswordDB: false
    oidcGroupsPrefix: true
    frontend:
      logoURL: https://s.giantswarm.io/brand/1/logo.svg
    {{- if .Values.isWorkloadCluster }}
    issuer: https://dex.{{ .Values.baseDomain }}
    {{- else }}
    issuer: https://{{ .Values.oidc.issuerAddress }}
    {{- end }}
    expiry:
      signingKeys: "{{ .Values.oidc.expiry.signingKeys }}"
      idTokens: "{{ .Values.oidc.expiry.idTokens }}"
    staticClients:
    {{- if .Values.oidc.staticClients.grafana.clientID }}
    - id: {{ .Values.oidc.staticClients.grafana.clientID }}
      public: true
      redirectURIs:
      - {{ .Values.oidc.staticClients.grafana.redirectURI }}
      name: grafana
    {{- end }}
    {{- if .Values.oidc.staticClients.gsCLIAuth.clientID }}
    - id: {{ .Values.oidc.staticClients.gsCLIAuth.clientID }}
      public: true
      name: gscliauth
    {{- end }}
    {{- if .Values.oidc.staticClients.happa.clientID }}
    - id: {{ .Values.oidc.staticClients.happa.clientID }}
      public: true
      redirectURIs:
      - {{ .Values.oidc.staticClients.happa.redirectURI }}
      - http://localhost:7000
      name: happa
    {{- end }}
    {{- if .Values.isManagementCluster }}
    - id: dex-k8s-authenticator
      redirectURIs:
      {{- if .Values.oidc.customer.enabled }}
      - https://{{ .Values.oidc.staticClients.dexK8SAuthenticator.clientAddress }}/callback
      {{- end }}
      {{- if .Values.oidc.giantswarm.connectorConfig.clientID }}
      - https://{{ .Values.oidc.staticClients.dexK8SAuthenticator.clientAddress }}/admin/callback
      {{- end }}
      name: dex-k8s-authenticator
      secret: {{ .Values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
      {{- if (or .Values.oidc.staticClients.gsCLIAuth.clientID .Values.oidc.staticClients.happa.clientID) }}
      trustedPeers:
      - {{ .Values.oidc.staticClients.gsCLIAuth.clientID }}
      - {{ .Values.oidc.staticClients.happa.clientID }}
      {{- end }}
    {{- end }}
    {{- if .Values.isWorkloadCluster }}
    - id: dex-k8s-authenticator
      name: dex-k8s-authenticator
      redirectURIs:
      - https://login.{{ .Values.baseDomain }}/callback
      secret: {{ .Values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
    {{- end }}
    connectors:
    {{- if .Values.oidc.giantswarm.connectorConfig.clientID }}
    - type: github
      id: giantswarm
      name: GitHub for Giant Swarm staff
      config:
        clientID: {{ .Values.oidc.giantswarm.connectorConfig.clientID }}
        clientSecret: {{ .Values.oidc.giantswarm.connectorConfig.clientSecret }}
        loadAllGroups: false
        {{- if .Values.isWorkloadCluster }}
        redirectURI: https://dex.{{ .Values.baseDomain }}/callback
        {{- else }}
        redirectURI: https://{{ .Values.oidc.issuerAddress }}/callback
        {{- end }}
        orgs:
        - name: giantswarm
          teams:
          - {{ .Values.oidc.giantswarm.connectorConfig.team }}
    {{- end }}
    {{- if .Values.oidc.customer.enabled }}
    - type: {{ .Values.oidc.customer.connectorType }}
      id: customer
      name: {{ .Values.oidc.customer.connectorName }}
      config:
        {{- .Values.oidc.customer.connectorConfig | nindent 8 }}
    {{- end }}
