{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.dex.name"  . }}
  labels:
  {{- include "dex.labels.common" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      relabelings:
      - replacement: {{ .Values.clusterID }}
        targetLabel: cluster_id
  selector:
    matchLabels:
  {{- include "dex.labels.selector" . | nindent 6 }}
{{- end }}
