apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
    {{- include "dex-app.labels.selector" . | nindent 4 }}
  name: {{ include "resource.dex.name" . }}
