apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    targetPort: http
    port: 32000
  - name: telemetry
    port: 5557
  selector:
    {{- include "dex.labels.selector" . | nindent 4 }}
