{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.dex.name"  . }}
  labels:
  {{- include "dex.labels.common" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      metricRelabelings:
      - targetLabel: cluster_id
        {{- if .Values.isManagementCluster }}
        {{- if (eq (kindOf .Values.managementCluster) "string") }}
        replacement: {{ .Values.managementCluster }}
        {{- else }}
        replacement: {{ .Values.managementCluster.name }}
        {{- end }}
        {{- else if eq (include "is-workload-cluster" .) "true" }}
        replacement: {{ .Values.clusterID }}
        {{- end }}
  selector:
    matchLabels:
  {{- include "dex.labels.selector" . | nindent 6 }}
{{- end }}
