apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.dex.name" . }}
  labels:
    {{- include "dex.labels.common" . | nindent 4 }}
    cluster_id: {{ $values.clusterID }}
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    targetPort: http
    port: 32000
  - name: metrics
    port: 5558
    targetPort: metrics
  selector:
    {{- include "dex.labels.selector" . | nindent 4 }}
