# Default values for dex
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

client:
  image:
    registry: quay.io
    name: giantswarm/dex-k8s-authenticator
    # tag with connector_id support
    tag: 1.2.0-giantswarm
    pullPolicy: IfNotPresent

dex:
  image:
    registry: quay.io
    name: giantswarm/dex
    tag: v2.24.0-giantswarm
    pullPolicy: IfNotPresent

extraVolumes: []
extraVolumeMounts: []
logoURI: http://styleguide.io/o/giantswarm/logo_simplified/giantswarm_logo_simplified.png

Installation:
  V1:
    GiantSwarm:
      OIDC:
        Kubernetes:
          API:
            Public: true
