# Default values for dex
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

client:
  image:
    registry: quay.io
    name: giantswarm/dex-k8s-authenticator
    tag: 1.4.0
    pullPolicy: IfNotPresent

dex:
  image:
    registry: quay.io
    name: giantswarm/dex
    tag: v2.28.1-giantswarm-2
    pullPolicy: IfNotPresent

extraVolumes: []
extraVolumeMounts: []
logoURI: https://s.giantswarm.io/brand/1/logo.svg

isManagementCluster: false
managementCluster:
  name: ""

ingress:
  tls:
    letsencrypt: true
    caPemB64: ""
    crtPemB64: ""
    keyPemB64: ""

oidc:
  issuerAddress: ""
  expiry:
    signingKeys: ""
    idTokens: ""
  staticClients:
    grafana:
      cliendID: ""
      redirectURI: ""
    gsCLIAuth:
      clientID: ""
    happa:
      clientID: ""
      redirectURI: ""
    dexK8SAuthenticator:
      clientAddress: ""
      clientSecret: ""
  giantswarm:
    connectorConfig:
      clientID: ""
      clientSecret: ""
      team: ""
    write_all_group: ""
  customer:
    enabled: false
    connectorType: ""
    connectorName: ""
    connectorConfig: ""
    write_all_group: ""

services:
  kubernetes:
    api:
      public: true
      address: ""
      internalAddress: ""
      caPem: ""
  happa:
    address: ""
  grafana:
    address: ""

registry:
  domain: docker.io
