# Default values for dex
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

client:
  image:
    registry: quay.io
    name: giantswarm/dex-k8s-authenticator
    tag: 1.4.0
    pullPolicy: IfNotPresent

dex:
  image:
    registry: quay.io
    name: giantswarm/dex
    tag: v2.35.3-gs1
    pullPolicy: IfNotPresent

extraVolumes: []
extraVolumeMounts: []
logoURI: https://s.giantswarm.io/brand/1/logo.svg

ingress:
  tls:
    letsencrypt: true
    clusterIssuer: ""
    caPemB64: ""
    crtPemB64: ""
    keyPemB64: ""

oidc:
  issuerAddress: ""
  expiry:
    signingKeys: 6h
    idTokens: 30m
  staticClients:
    grafana:
      cliendID: ""
      redirectURI: ""
    gsCLIAuth:
      clientID: "zQiFLUnrTFQwrybYzeY53hWWfhOKWRAU"
      address: http://localhost:8085/oauth/callback
    happa:
      clientID: ""
      redirectURI: ""
    dexK8SAuthenticator:
      clientAddress: ""
      clientSecret: "default-client-dex-authenticator-secret"
  # Giant Swarm OIDC values to run DEX in the management clusters
  giantswarm:
    connectorConfig:
      clientID: ""
      clientSecret: ""
      team: ""
    write_all_group: ""
    connectors: []
  customer:
    enabled: false
    connectorType: ""
    connectorName: ""
    connectorConfig: ""
    write_all_group: ""
    connectors: []

# Note that the public address in Giant Swarm management cluster configurations already includes the port
services:
  kubernetes:
    api:
      public: true
      address: ""
      internalAddress: ""
      caPem: ""
      port: 443
  happa:
    address: ""
  grafana:
    address: ""

registry:
  domain: docker.io

# Giant Swarm properties for management clusters
isManagementCluster: false
managementCluster:
  name: ""

# Giant Swarm properties for workload clusters
isWorkloadCluster: false
