# Default values for dex
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

client:
  image:
    registry: quay.io
    name: giantswarm/dex-k8s-authenticator
    tag: 1.4.0
    pullPolicy: IfNotPresent

dex:
  image:
    registry: quay.io
    name: giantswarm/dex-app
    pullPolicy: IfNotPresent

extraVolumes: []
extraVolumeMounts: []
logoURI: https://s.giantswarm.io/brand/1/logo.svg

ingress:
  ingressClassName: "nginx"
  externalDNS: false
  tls:
    letsencrypt: true
    clusterIssuer: "letsencrypt-giantswarm"
    caPemB64: ""
    crtPemB64: ""
    keyPemB64: ""
    externalSecret:
      enabled: false
  annotations: {}

oidc:
  issuerAddress: ""
  expiry:
    signingKeys: 6h
    idTokens: 30m
  staticClients:
    gitopsui:
      clientID: ""
      clientSecret: ""
      redirectURI: ""
    grafana:
      cliendID: ""
      redirectURI: ""
    gsCLIAuth:
      clientID: "zQiFLUnrTFQwrybYzeY53hWWfhOKWRAU"
      address: http://localhost:8085/oauth/callback
    happa:
      clientID: ""
      redirectURI: ""
    dexK8SAuthenticator:
      clientAddress: ""
      clientSecret: "default-client-dex-authenticator-secret"
  extraStaticClients: []
  # Giant Swarm OIDC values to run DEX in the management clusters
  giantswarm:
    connectorConfig:
      clientID: ""
      clientSecret: ""
      team: ""
    connectors: []
  customer:
    enabled: false
    connectorType: ""
    connectorName: ""
    connectorConfig: ""
    connectors: []

# Note that the public address in Giant Swarm management cluster configurations already includes the port
services:
  kubernetes:
    api:
      public: true
      address: ""
      internalAddress: ""
      caPem: ""
      port: 443
  happa:
    address: ""
  grafana:
    address: ""
  gitopsui:
    address: ""
  backstage:
    address: []

registry:
  domain: gsoci.azurecr.io

# Giant Swarm properties for management clusters
isManagementCluster: false
managementCluster:
  name: ""

# Giant Swarm properties for workload clusters
isWorkloadCluster: false

# Enable the deployment of the dex k8s authenticator together with dex
# Please note that this app is deprecated and will be removed in the future
deployDexK8SAuthenticator: false

cluster:
  proxy:
    http: ""
    https: ""
    noProxy: ""

global:
  podSecurityStandards:
    enforced: false
