{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "dexk8sauth.customer.labels.common" . | nindent 4 }}
  name: {{ include "resource.dexk8sauth.customer.name" . }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include  "resource.dexk8sauth.customer.psp.name" . }}
  verbs:
  - use
{{ end }}
