{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    secretName: {{ include "resource.default.name" . }}-le
    {{- else }}
    secretName: {{ include "resource.default.name" . }}
    {{- end }}
  rules:
  - host: {{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "resource.default.name" . }}
          servicePort: http
{{ end }}
