{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.dexk8sauth.customer.name" . }}
  labels:
    {{- include "dexk8sauth.customer.labels.common" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "dexk8sauth.customer.labels.selector" . | nindent 4 }}
{{ end }}
