{{- if not .Values.ingress.tls.letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
  name: {{ include "resource.dexk8sauth.name" . }}
data:
  ca.crt: {{ .ingress.tls.caPemB64 }} 
  tls.crt: {{ .ingress.tls.crtPemB64 }} 
  tls.key: {{ .ingress.tls.keyPemB64 }} 
{{- end }}
