{{- if not .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
  name: {{ include "resource.dexk8sauth.name" . }}
data:
  ca.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CAPem | b64enc | quote }}
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
{{- end }}
