{{- if not .Values.ingress.tls.letsencrypt }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
  name: {{ include "resource.dexk8sauth.name" . }}
data:
  ca.crt: {{ .Values.ingress.tls.caPemB64 | quote }}
  tls.crt: {{ .Values.ingress.tls.crtPemB64 | quote }}
  tls.key: {{ .Values.ingress.tls.keyPemB64 | quote }}
{{- end }}
