{{- if .Values.deployDexK8SAuthenticator }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
  name: {{ include "resource.dexk8sauth.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.dexk8sauth.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.dexk8sauth.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
