{{ if .Values.oidc.customer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.dexk8sauth.name" . }}-customer
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: "/"
    debug: "false"
    logo_uri: {{ .Values.logoURI }}
    {{- if not .Values.ingress.tls.letsencrypt }}
    trusted_root_ca_file: /app/ssl/ca.crt
    {{- end }}
    clusters:
    - name: {{ .Values.managementCluster.name }}
      short_description: "{{ .Values.managementCluster.name }} management cluster"
      description: "Management cluster Kubernetes API for installation '{{ .Values.managementCluster.name }}', as a Giant Swarm customer"
      client_id: dex-k8s-authenticator
      client_secret: {{ .Values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
      connector_id: customer
      issuer: https://{{ .Values.oidc.issuerAddress }}
      {{if .Values.services.kubernetes.api.public }}
      k8s_master_uri: https://{{ .Values.services.kubernetes.api.address }}
      {{ else }}
      k8s_master_uri: https://{{ .Values.services.kubernetes.api.internalAddress }}
      {{ end }}
      k8s_ca_pem: {{ toYaml .Values.services.kubernetes.api.caPem | indent 8 }}
      redirect_uri: https://{{ .Values.oidc.staticClients.dexK8SAuthenticator.clientAddress }}/callback
{{ end }}
