{{- if .Values.oidc.staticClients.dexK8SAuthenticator.enableDeployment }}
{{ if .Values.oidc.customer.enabled }}
{{- if .Values.oidc.customer.connectors -}}
{{ $values := .Values }}
{{ $resource := . }}
{{- range .Values.oidc.customer.connectors }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.dexk8sauth.name" $resource }}-{{ .id }}
  labels:
    {{- include "dexk8sauth.labels.common" $resource | nindent 4 }}
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: "/"
    debug: "false"
    logo_uri: {{ $values.logoURI }}
    {{- if not $values.ingress.tls.letsencrypt }}
    trusted_root_ca_file: /app/ssl/ca.crt
    {{- end }}
    clusters:
    {{- if $values.isManagementCluster }}
    - client_id: dex-k8s-authenticator
      {{- if (eq (kindOf $values.managementCluster) "string") }}
      name: {{ $values.managementCluster }}
      description: "Management Cluster Kubernetes API for installation '{{ $values.managementCluster }}', as a Giant Swarm customer"
      short_description: "{{ $values.managementCluster }} management cluster"
      {{- else }}
      name: {{ $values.managementCluster.name }}
      description: "Management Cluster Kubernetes API for installation '{{ $values.managementCluster.name }}', as a Giant Swarm customer"
      short_description: "{{ $values.managementCluster.name }} management cluster"    
      {{- end }}
      client_secret: {{ $values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
      connector_id: {{ .id }}
      issuer: https://{{ $values.oidc.issuerAddress }}
      {{- if $values.services.kubernetes.api.public }}
      k8s_master_uri: {{ $values.services.kubernetes.api.address }}
      {{- else }}
      k8s_master_uri: {{ $values.services.kubernetes.api.internalAddress }}:{{ $values.services.kubernetes.api.port }}
      {{- end }}
      k8s_ca_pem: ${KUBERNETES_CACERT}
      redirect_uri: https://{{ $values.oidc.staticClients.dexK8SAuthenticator.clientAddress }}/callback
    {{- else if eq (include "is-workload-cluster" $resource) "true" }}
    - name: {{ $values.clusterID }}
      description: "Cluster Kubernetes API {{ $values.clusterID }}"
      short_description: "{{ $values.clusterID }} cluster"
      client_id: dex-k8s-authenticator
      client_secret: {{ $values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
      connector_id: {{ .id }}
      issuer: https://dex.{{ $values.baseDomain }}
      {{- if $values.services.kubernetes.api.public }}
      k8s_master_uri: https://api.{{ $values.baseDomain }}:{{ $values.services.kubernetes.api.port }}
      {{- else }}
      k8s_master_uri: {{ $values.services.kubernetes.api.internalAddress }}:{{ $values.services.kubernetes.api.port }}
      {{- end }}
      k8s_ca_pem: {{ toYaml $values.clusterCA | indent 8 }}
      redirect_uri: https://login.{{ $values.baseDomain }}/callback
    {{- end }}
{{- end }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.dexk8sauth.name" . }}-customer
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: "/"
    debug: "false"
    logo_uri: {{ .Values.logoURI }}
    {{- if not .Values.ingress.tls.letsencrypt }}
    trusted_root_ca_file: /app/ssl/ca.crt
    {{- end }}
    clusters:
    {{- if .Values.isManagementCluster }}
    - client_id: dex-k8s-authenticator
      {{- if (eq (kindOf .Values.managementCluster) "string") }}
      name: {{ .Values.managementCluster }}
      description: "Management Cluster Kubernetes API for installation '{{ .Values.managementCluster }}', as a Giant Swarm customer"
      short_description: "{{ .Values.managementCluster }} management cluster"
      {{- else }}
      name: {{ .Values.managementCluster.name }}
      description: "Management Cluster Kubernetes API for installation '{{ .Values.managementCluster.name }}', as a Giant Swarm customer"
      short_description: "{{ .Values.managementCluster.name }} management cluster"    
      {{- end }}
      client_secret: {{ .Values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
      connector_id: customer
      issuer: https://{{ .Values.oidc.issuerAddress }}
      {{- if .Values.services.kubernetes.api.public }}
      k8s_master_uri: {{ .Values.services.kubernetes.api.address }}
      {{- else }}
      k8s_master_uri: {{ .Values.services.kubernetes.api.internalAddress }}:{{ .Values.services.kubernetes.api.port }}
      {{- end }}
      k8s_ca_pem: ${KUBERNETES_CACERT}
      redirect_uri: https://{{ .Values.oidc.staticClients.dexK8SAuthenticator.clientAddress }}/callback
    {{- else if eq (include "is-workload-cluster" .) "true" }}
    - name: {{ .Values.clusterID }}
      description: "Cluster Kubernetes API {{ .Values.clusterID }}"
      short_description: "{{ .Values.clusterID }} cluster"
      client_id: dex-k8s-authenticator
      client_secret: {{ .Values.oidc.staticClients.dexK8SAuthenticator.clientSecret }}
      connector_id: customer
      issuer: https://dex.{{ .Values.baseDomain }}
      {{- if .Values.services.kubernetes.api.public }}
      k8s_master_uri: https://api.{{ .Values.baseDomain }}:{{ .Values.services.kubernetes.api.port }}
      {{- else }}
      k8s_master_uri: {{ .Values.services.kubernetes.api.internalAddress }}:{{ .Values.services.kubernetes.api.port }}
      {{- end }}
      k8s_ca_pem: {{ toYaml .Values.clusterCA | indent 8 }}
      redirect_uri: https://login.{{ .Values.baseDomain }}/callback
    {{- end }}
{{ end }}
{{ end }}
{{- end }}
