apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.dexk8sauth.name" . }}
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}
    {{- if .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
    secretName: {{ include "resource.dexk8sauth.name" . }}-le
    {{- else }}
    secretName: {{ include "resource.dexk8sauth.name" . }}
    {{- end }}
  rules:
  - host: {{ .Values.Installation.V1.GiantSwarm.OIDC.ClientAddress }}
    http:
      paths:
      - path: /admin
        backend:
          serviceName: {{ include "resource.dexk8sauth.name" . }}-giantswarm
          servicePort: http
{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
      - path: /
        backend:
          serviceName: {{ include "resource.dexk8sauth.name" . }}-customer
          servicePort: http
{{ end }}
