{{- if .Values.oidc.staticClients.dexK8SAuthenticator.enableDeployment }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dexk8sauth.labels.common" . | nindent 4 }}
  name: {{ include "resource.dexk8sauth.name" . }}
{{- end }}
