{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "dexauthenticator.labels" . | indent 4 }}
  name: {{ include "resource.dexauthenticator.name" . }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include  "resource.dexauthenticator.psp.name" . }}
  verbs:
  - use
{{ end }}
