{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.dexauthenticator.name" . }}
  labels:
    {{- include "dexauthenticator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "dexauthenticator.labels.selector" . | indent 4 }}
{{ end }}
