{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
{{- if not .Values.Installation.V1.GiantSwarm.OIDC.Letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.dex.name" . }}-tls
data:
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
{{- end }}
{{ end }}
