{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "dex.labels" . | indent 4 }}
  name: {{ include "resource.dex.name" . }}
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "resource.dex.psp.name" . }}
  verbs:
  - use
{{ end }}
