{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dex.labels" . | indent 4 }}
  name: {{ include "resource.dex.name" . }}
{{ end }}
